#!/usr/bin/env bash
# displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th # loop iteration
# displays 9 and then bad luck from Japan for the 9th # loop iteration
# displays 17 and then bad luck from Italy for the 
# 17th loop iteration

count=1
while [ $count -lt 20 ]
do
    if [ $count -eq 4 ]
    then
        echo "bad luck form China"
    elif [ $count -eq 9 ]
    then
        echo "bad luck form Japan"
    elif [ $count -eq 17 ]
    then
        echo "bad luck form Italy"
        fi
        (( count++ ))
done
